title: web絵　第1項/My painting record, paragraph 1.
email: ...
description: PCで描いた絵をここに記録します。<br>
このサイトはダークモードにしたり、ブラウザーを変えると見え方が少し変わります。<br> 
pc,androidのスペックでも絵が変化します。絵はほぼsvg形式で書かれています。<br>
This is where I record the pictures I draw on my PC.<br>
This site looks a little different when you put it in dark mode or change browsers.<br>
The picture changes even with PC and Android specs.<br>
The picture is written almost in SVG format.
baseurl: ...
url: https://itou332.github.io/top_page/
twitter_username: ...
github_username: itou332
author: ...

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock

# pagination
  limit: 0
  sort_field: 'date'
  title: ':web絵　第1項/My painting record, paragraph 1.'
 

# multilang
languages: ['ja', 'ko', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false

