name: Update Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  update-cloudflare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PAGE_NAME: ${{ secrets.CF_PAGE_NAME }}
        run: |
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ env.CF_ACCOUNT_ID }}/pages/sites" \
          -H "Authorization: Bearer ${{ env.CLOUDFLARE_API_TOKEN }}" \
          -d '{"page":"${{ env.CF_PAGE_NAME }}","origin":"https://github.com/$GITHUB_REPOSITORY"}'

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
